# Generated by Django 5.0.6 on 2024-06-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("iata_code", models.CharField(max_length=3)),
                ("icao_code", models.CharField(max_length=4)),
            ],
        ),
    ]
